version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ergracer
      POSTGRES_USER: ergracer
      POSTGRES_PASSWORD: password123
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ergracer -d ergracer"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://ergracer:password123@postgres:5432/ergracer?sslmode=disable
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      APP_URL: http://localhost:8080
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data: